---

- name: Ensure Redis is installed from Fedora repository
  ansible.builtin.dnf:
    state: present
    name: redis
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Check if Redis configuration was updated by RPM
  ansible.builtin.stat:
    path: /etc/redis/redis.conf.rpmnew
  register: redis_conf_rpmnew

- name: Ensure latest Redis configuration from RPM is used
  ansible.builtin.copy:
    remote_src: true
    src: /etc/redis/redis.conf.rpmnew
    dest: /etc/redis/redis.conf
  when: redis_conf_rpmnew.stat.exists

- name: Ensure Redis is configured
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\\s*{{ item.option }}\s'
    line: '{{ item.option }} {{ item.value }}'
  with_items:
    - option: unixsocket
      value: /var/run/redis/redis.sock
    - option: unixsocketperm
      value: 770
    - option: port
      value: 0
    - option: syslog-enabled
      value: "yes"
    - option: logfile
      value: "/dev/null"

- name: Ensure Redis service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/redis.service.d
    state: directory

- name: Ensure Redis service configuration is present
  ansible.builtin.copy:
    src: redis_service.conf
    dest: /etc/systemd/system/redis.service.d/redis.conf

- name: Ensure Redis is started and enabled at boot
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true
    daemon_reload: true

- name: SELinux configuration
  ansible.builtin.include_tasks: selinux.yml

- name: Ensure user is member of Redis group
  ansible.builtin.user:
    name: "{{ redis_user }}"
    groups: redis
    append: true
  when: redis_user is defined

- name: Ensure Redis "rpmnew" and "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/redis/redis.conf.rpmnew
    - /etc/redis/redis.conf.rpmsave
