---

- name: Ensure Redis is installed from Fedora repository
  dnf:
    state: present
    name: redis
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure Redis is configured to use unix socket only
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^{{ item.option }}\s'
    line: '{{ item.option }} {{ item.value }}'
  with_items:
    - option: unixsocket
      value: /var/run/redis/redis.sock
    - option: unixsocketperm
      value: 770
    - option: port
      value: 0

- name: Ensure Redis service parent directory is present
  file:
    path: /etc/systemd/system/redis.service.d
    state: directory

- name: Ensure Redis service configuration is present
  copy:
    src: redis_service.conf
    dest: /etc/systemd/system/redis.service.d/redis.conf

- name: Ensure Redis is started and enabled at boot
  systemd:
    name: redis
    state: started
    enabled: true
    daemon_reload: true

- include_tasks: selinux.yml

- name: Ensure user is member of Redis group
  user:
    name: "{{ redis_user }}"
    groups: redis
    append: true
  when: redis_user is defined
