---

- name: Ensure netdata user is member of redis group
  ansible.builtin.user:
    name: netdata
    groups: redis
    append: true

- name: Ensure Netdata configuration directory is present
  ansible.builtin.file:
    path: /etc/netdata/go.d
    state: directory
    mode: '0755'

- name: Ensure Netdata collectors are configured
  ansible.builtin.template:
    src: netdata_redis.conf.j2
    dest: /etc/netdata/go.d/redis.conf
    mode: '0644'
  notify: netdata_restarted
