---

- name: Ensure musicplayer user is present
  ansible.builtin.user:
    name: musicplayer

- name: Ensure the music player and its dependencies are installed
  ansible.builtin.dnf:
    state: present
    name:
      - "{{ musicplayer_package }}"
      - alsa-utils
      - sway
      - plymouth-system-theme
      - polkit
      - playerctl
      - "@fonts"
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure sound is managed by ALSA only
  ansible.builtin.dnf:
    state: "{{ musicplayer_alsa_only | ternary('absent', 'present') }}"
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulseaudio
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure Sway configuration directory is present
  ansible.builtin.file:
    path: /home/musicplayer/.config/sway
    state: directory
    owner: musicplayer
    group: musicplayer

- name: Ensure Sway configuration is present
  ansible.builtin.template:
    src: config.j2
    dest: /home/musicplayer/.config/sway/config
    owner: musicplayer
    group: musicplayer

- name: Ensure dmix is disabled in ALSA configuration
  ansible.builtin.copy:
    src: asound.conf
    dest: /etc/asound.conf

- name: Ensure ALSA RPM package files metadata are in sync
  ansible.builtin.command: rpm --restore alsa-lib # noqa command-instead-of-module
  changed_when: false

- name: Ensure HDMI sound is disabled
  ansible.builtin.copy:
    src: alsa-blacklist.conf
    dest: /etc/modprobe.d/alsa-blacklist.conf
  when: musicplayer_disable_hdmi_sound | bool

- name: Serial display configuration
  ansible.builtin.include_tasks: serial_display.yml
  when: musicplayer_serial_display | bool

- name: Ensure musicplayer service unit is present
  ansible.builtin.template:
    src: musicplayer.service.j2
    dest: /etc/systemd/system/musicplayer.service

- name: Ensure previous getty-based configuration is absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /home/musicplayer/.bash_profile
    - /home/musicplayer/musicplayer.sh
    - /etc/systemd/system/getty@tty1.service.d/musicplayer.conf
    - /etc/systemd/system/getty@tty1.service.d/alsa-unmute.conf
    - /etc/systemd/system/getty@tty1.service.d

- name: Ensure systemd target is graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Ensure musicplayer service is enabled at boot
  ansible.builtin.systemd:
    name: musicplayer
    enabled: true

- name: Ensure musicplayer service is restarted
  ansible.builtin.systemd:
    name: musicplayer
    state: started
    daemon_reload: true
