---

- name: Ensure Nginx is installed from Fedora repository
  dnf:
    state: present
    name: nginx
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure default "server" in Nginx configuration is absent
  blockinfile:
    path: /etc/nginx/nginx.conf
    state: absent
    marker: '{mark}'
    marker_begin: "    server {"
    marker_end: "#    }"

- include_tasks: tls_certificates.yml

- name: Ensure Nginx service parent directory is present
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Ensure Nginx systemd service configuration is present
  template:
    src: nginx_service.conf.j2
    dest: /etc/systemd/system/nginx.service.d/nginx.conf

- name: Ensure Nginx default site configuration is absent
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Ensure Nginx site configuration is present
  template:
    src: nginx-site.conf.j2
    dest: "{{ _site_conf }}"
    mode: 0640

- name: Ensure Nginx user is member of site group
  user:
    name: nginx
    groups: "{{ nginx_site_user }}"
    append: true
  when: nginx_site_user is defined

- include_tasks: selinux.yml

- name: Ensure Nginx service is started and enabled at boot
  block:
    - name: Ensure Nginx service is started and enabled at boot
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true
      tags: molecule-notest
  rescue:
    - name: Show service status on error
      command: systemctl status nginx --no-pager  # noqa command-instead-of-module
      failed_when: true

- name: Ensure Fail2ban directory is present
  file:
    path: /etc/fail2ban/jail.d/
    state: directory

- name: Ensure Fail2ban is configured
  copy:
    src: nginx.local
    dest: /etc/fail2ban/jail.d/nginx.local

- include_tasks: firewall.yml
