---

- name: Ensure Nginx is installed from Fedora repository
  ansible.builtin.dnf:
    state: present
    name: nginx
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure default "server" in Nginx configuration is absent
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    state: absent
    marker: '{mark}'
    marker_begin: "    server {"
    marker_end: "#    }"

- name: Ensure logs are configured
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^\\s*error_log "
      line: "error_log stderr {{ nginx_error_log_level }};"
    - regexp: "^\\s*access_log "
      line: "    access_log {% if nginx_access_log %}syslog:server=unix:/dev/log{% else %}off{% endif %};"

- name: TLS certificate configuration
  ansible.builtin.include_tasks: tls_certificates.yml

- name: Ensure Nginx service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Ensure Nginx systemd service configuration is present
  ansible.builtin.template:
    src: nginx_service.conf.j2
    dest: /etc/systemd/system/nginx.service.d/nginx.conf

- name: Ensure Nginx default site configuration is absent
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Ensure Nginx site configuration is present
  ansible.builtin.template:
    src: nginx-site.conf.j2
    dest: "{{ _site_conf }}"
    mode: "0640"

- name: Ensure Nginx user is member of site group
  ansible.builtin.user:
    name: nginx
    groups: "{{ nginx_site_user }}"
    append: true
  when: nginx_site_user is defined

- name: SELinux configuration
  ansible.builtin.include_tasks: selinux.yml

- name: Ensure Nginx service is started and enabled at boot
  block:
    - name: Ensure Nginx service is started and enabled at boot
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true
  rescue:
    - name: Show service status on error
      ansible.builtin.command: journalctl -u nginx --no-pager  # noqa command-instead-of-module
      failed_when: true
      changed_when: false

- name: Ensure Fail2ban directory is present
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d/
    state: directory

- name: Ensure Fail2ban is configured
  ansible.builtin.copy:
    src: nginx.local
    dest: /etc/fail2ban/jail.d/nginx.local

- name: Firewall configuration
  ansible.builtin.include_tasks: firewall.yml
