---
galaxy_info:
  author: JGoutin
  description: "This role initializes a new Fedora host by performing some
                common configuration tasks."
  license: GPL-3.0
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - "38"
        - "37"
  galaxy_tags:
    - fedora
    - system

dependencies: []
collections:
  - ansible.legacy
