---

- name: Ensure ClamAV is installed from Fedora repository
  ansible.builtin.dnf:
    state: present
    name:
      - clamav
      - clamav-update
      - clamav-unofficial-sigs
      - clamd
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure ClamAV virus database is up to date
  # Note: Auto-updated by "/etc/cron.d/clamav-update"
  ansible.builtin.command: freshclam
  changed_when: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful
  tags: molecule-notest  # Sometime, fail on GitHub action due to rate limit

- name: Ensure SELinux is configured to allow system scan
  ansible.posix.seboolean:
    name: antivirus_can_scan_system
    state: true
    persistent: true

- name: Ensure ClamAV Scan service is configured
  ansible.builtin.lineinfile:
    path: /etc/clamd.d/scan.conf
    regexp: "^#?{{ item.split(' ')[0] | trim('#') }} "
    line: "{{ item }}"
  with_items:
    - "#Example"
    - "LocalSocket /var/run/clamd.scan/clamd.sock"
    - "LocalSocketGroup virusgroup"
    - "LocalSocketMode 660"

- name: Ensure Nginx service is started and enabled at boot
  block:
    - name: Ensure ClamAV Scan service is started and enabled at boot
      ansible.builtin.systemd:
        name: clamd@scan
        state: started
        enabled: true
      tags: molecule-notest # Requires "freshclam" first
  rescue:
    - name: Show service status on error
      ansible.builtin.command: journalctl -u clamd@scan --no-pager  # noqa command-instead-of-module
      failed_when: true
      changed_when: false
