{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN echo "retries=0" >> /etc/dnf/dnf.conf && \
echo "fastestmirror=true" >> /etc/dnf/dnf.conf && \
echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf && \
dnf --assumeyes install --setopt=install_weak_deps=False \
    checkpolicy \
    policycoreutils \
    python3 \
    python3-dnf \
    sudo
