---
kodi_ir_remote: false
kodi_remote_control: false

# Define firewalld zone value to use depending on specified source
kodi_firewalld_zone: "{{ kodi_firewalld_source is defined |
                      ternary('kodi', 'internal') }}"
