---

- name: Ensure RPMFusion-Free repository is present
  ansible.builtin.dnf:
    state: present
    name: "https://download1.rpmfusion.org/free/\
      {{ (ansible_distribution == 'Fedora') | ternary('fedora', 'el') }}\
      /rpmfusion-free-release-{{ ansible_distribution_major_version }}\
      .noarch.rpm"
    disable_gpg_check: true
  retries: 10
  delay: 1
  register: _
  until: _ is successful
  when: rpmfusion_free | bool

- name: Ensure RPMFusion-Nonfree repository is present
  ansible.builtin.dnf:
    state: present
    name: "https://download1.rpmfusion.org/nonfree/\
      {{ (ansible_distribution == 'Fedora') | ternary('fedora', 'el') }}\
      /rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}\
      .noarch.rpm"
    disable_gpg_check: true
  retries: 10
  delay: 1
  register: _
  until: _ is successful
  when: rpmfusion_nonfree | bool
