---
namespace: jgoutin
name: home
description: Home free software self-hosting.
version: 0.0.0  # Set by deployment pipeline
readme: readme.md
authors:
  - jgoutin
license:
  - GPL-3.0-or-later
tags:
  - application
  - linux
  - system
  - fedora
  - clamav
  - coturn
  - dovecot
  - fail2ban
  - kodi
  - lollypop
  - mpd
  - nextcloud
  - nginx
  - php_fpm
  - postfix
  - postgresql
  - redis
  - rpmfusion
  - security
  - squid

repository: https://github.com/jgoutin/ansible_home
documentation: https://jgoutin.github.io/ansible_home/
issues: https://github.com/jgoutin/ansible_home/issues
dependencies:
  ansible.posix: ">=1.0.0"
build_ignore:
  - .flake8
  - .gitignore
  - .github
  - .idea
  - .project
  - .pydevproject
  - .settings
  - .spyderproject
  - .spyproject
  - .vscode
  - .vagrant
  - Vagrantfile
  - playbook.yml
  - "*-playbook.yml"
  - "*.tar.gz"
  - tests
  - _config.yml
  - index.md
  - "*.sh"
