---
nginx_can_connect_ldap: false
nginx_can_network_connect: false
nginx_can_network_connect_db: false
nginx_can_network_memcache: false
nginx_can_sendmail: false
nginx_can_use_cifs: false
nginx_can_use_fusefs: false
nginx_can_use_gpg: false
nginx_client_body_timeout: 60s
nginx_client_header_timeout: 60s
nginx_domain_can_mmap_files: false
nginx_hardening: false
nginx_limit_conn_per_ip: 100
nginx_limit_req_per_ip_burst: 1000
nginx_limit_req_per_ip_delay: nodelay
nginx_limit_req_per_ip_rate: 1000r/s
nginx_php_fpm: false
nginx_read_user_content: false
nginx_resolver: 127.0.0.1
nginx_security_header_content_security_policy: false
nginx_security_header_content_security_policy_value: "default-src 'none';\
                                                      frame-ancestors 'none';\
                                                      base-uri 'self';\
                                                      script-src 'self';\
                                                      style-src 'self';\
                                                      media-src 'self';\
                                                      font-src 'self';\
                                                      img-src 'self';\
                                                      form-action 'self';"
nginx_security_header_feature_policy: false
nginx_security_header_feature_policy_value: "geolocation none;\
                                             midi none;\
                                             notifications none;\
                                             push none;\
                                             sync-xhr none;\
                                             microphone none;\
                                             camera none;\
                                             magnetometer none;\
                                             gyroscope none;\
                                             speaker none;\
                                             vibrate none;\
                                             fullscreen self;\
                                             payment none;"
nginx_security_header_permission_policy: false
nginx_security_header_permission_policy_value: "geolocation(),\
                                                midi(),\
                                                notifications(),\
                                                push(),\
                                                sync-xhr(),\
                                                microphone(),\
                                                camera(),\
                                                magnetometer(),\
                                                gyroscope(),\
                                                speaker(),\
                                                vibrate(),\
                                                fullscreen(self),\
                                                payment()"
nginx_security_header_public_key_pins: false
nginx_security_header_public_key_pins_backup_pins: []
nginx_security_header_public_key_pins_max_age: 2592000
nginx_security_header_referrer_policy: true
nginx_security_header_x_content_type_options: true
nginx_security_header_x_download_options: true
nginx_security_header_x_frame_options: true
nginx_security_header_x_permitted_cross_domain_policies: true
nginx_security_header_x_robots_tag: true
nginx_security_header_x_xss_protection: true
nginx_unified: false

# Define firewalld zone value to use depending on specified source
nginx_firewalld_zone: "{{ nginx_firewalld_source is defined |
                       ternary('nginx', 'public') }}"

# Internal values
_tls_crt: "/etc/pki/tls/certs/{{ nginx_site }}.crt"
_tls_key: "/etc/pki/tls/private/{{ nginx_site }}.key"
_tls_ca: "/etc/pki/tls/certs/{{ nginx_site }}.trust.crt"
_site_conf: "/etc/nginx/conf.d/{{ nginx_site }}.conf"
