{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN echo "retries=0" >> /etc/dnf/dnf.conf && \
dnf --assumeyes install --setopt=install_weak_deps=False \
    python3 \
    python3-dnf \
    sudo \
    bash \
    iproute \
    systemd \
