---

- name: Get TURN credentials from Nextcloud if any
  ansible.builtin.command: /usr/bin/php occ -n config:app:get spreed turn_servers
  args:
    chdir: /var/www/nextcloud/
  become: true
  become_user: nextcloud
  failed_when: false
  changed_when: false
  register: _coturn_secret

- name: Set TURN credentials as fact
  ansible.builtin.set_fact:
    nextcloud_coturn_secret: "{{ ((_coturn_secret.stdout | trim() != '') |
                              ternary(_coturn_secret.stdout, [{'secret': lookup('password', '/dev/null chars=ascii_lowercase,digits length=32')}] | to_json) | from_json)[0]['secret'] }}"
  no_log: true

- name: Ensure CoTURN is installed
  ansible.builtin.include_role:
    name: jgoutin.home.coturn
  vars:
    coturn_realm: "{{ nextcloud_domain }}"
    coturn_static_auth_secret: "{{ nextcloud_coturn_secret }}"
    coturn_firewalld_zone: "{{ nginx_firewalld_source is defined | ternary('nginx', 'public') }}"
    coturn_tls_certificate: "{{ nginx_ssl_certificate | default(omit) }}"
    coturn_tls_certificate_key: "{{ nginx_ssl_certificate_key | default(omit) }}"
    coturn_total_quota: "100"
