---

- name: Ensure ClamAV is installed
  ansible.builtin.include_role:
    name: jgoutin.home.clamav
  when: '"files_antivirus" in nextcloud_applications'

- name: Coturn configuration
  ansible.builtin.include_tasks: coturn.yml
  when: '"spreed" in nextcloud_applications'
