---

# Workaround: https://github.com/ansible/ansible/issues/10374
- name: Get static role path
  set_fact:
    nexcloud_role_path: "{{ role_path }}"

- name: Get Nextcloud config file information
  stat:
    path: /var/www/nextcloud/config/config.php
  register: _config_php

- name: Ensure Nextcloud user is present
  user:
    name: nextcloud

- name: Ensure Nextcloud var directory is present
  file:
    path: /var/lib/nextcloud
    mode: 0755
    setype: var_lib_t
    state: directory

- include_tasks: dependencies.yml

- include_tasks: dependencies_apps.yml

- include_tasks: install.yml

- include_tasks: fail2ban.yml

- name: Ensure services are restarted
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  changed_when: false
  with_items:
    - php-fpm
    - nginx

- include_tasks: config.yml

- include_tasks: config_apps.yml

- include_tasks: maintenance.yml

- name: Ensure Nextcloud database is properly optimized
  command: "/usr/bin/php occ -n {{ item }}"
  args:
    chdir: /var/www/nextcloud/
  become: true
  become_user: nextcloud
  changed_when: false
  with_items:
    - maintenance:mode --on
    - db:add-missing-indices
    - db:add-missing-columns
    - db:add-missing-primary-keys
    - db:convert-filecache-bigint
    - maintenance:mode --off
