---

- name: Ensure MariaDB is installed from Fedora repository
  ansible.builtin.dnf:
    state: present
    name: mariadb-server
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure MariaDB service is started and enabled at boot
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true

- name: Ensure Ansible "python3-mysql" requirement is installed
  ansible.builtin.dnf:
    state: present
    name: python3-mysql
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _mysql_python3
  until: _mysql_python3 is successful

- name: Ensure database is configured
  block:

    - name: Ensure MariaDB database is present
      community.mysql.mysql_db:
        name: "{{ mariadb_database }}"
        state: present
      when: mariadb_database is defined

    - name: Ensure MariaDB database user is present
      community.mysql.mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        priv: '{{ mariadb_database }}.*:ALL'
        state: present
      when: mariadb_user is defined

  always:
    - name: Ensure Ansible "python3-mysql" requirement is removed
      ansible.builtin.dnf:
        state: absent
        name: python3-mysql
      when: _mysql_python3.changed  # noqa no-handler
