---
galaxy_info:
  author: JGoutin
  description: This Ansible role installs a Nexctloud server on Fedora.
  license: GPL-3.0
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - "36"
        - "37"
  galaxy_tags:
    - fedora
    - system
    - nextcloud

dependencies: []
