---
# Inspired by https://github.com/graysky2/kodi-standalone-service

- name: Ensure kodi service unit is present
  ansible.builtin.copy:
    src: kodi.service
    dest: /etc/systemd/system/kodi.service

- name: Ensure Kodi service is restarted and enabled at boot
  ansible.builtin.systemd:
    name: kodi.service
    state: started
    enabled: true
    daemon_reload: true

- name: Ensure systemd target is graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Ensure previous X11 based configuration is absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/getty@tty1.service.d/"
    - /home/kodi/.xinitrc
    - /usr/local/bin/kodi-logout
