---

- name: Ensure RpmFusion-free repository is installed
  ansible.builtin.include_role:
    name: jgoutin.home.rpmfusion
  vars:
    rpmfusion_free: true

- name: Ensure MPD is installed
  ansible.builtin.dnf:
    state: present
    name:
      - mpd
      - mpc
      - alsa-utils
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure MPD is configured
  ansible.builtin.template:
    src: mpd.conf.j2
    dest: /etc/mpd.conf
    owner: root
    group: mpd
    mode: "0740"

- name: Ensure MPD service directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/mpd.service.d/
    state: directory

- name: Ensure ALSA unmute is enabled in MPD service
  ansible.builtin.template:
    src: alsa-unmute.conf.j2
    dest: "/etc/systemd/system/mpd.service.d/alsa-unmute.conf"

- name: Ensure SELinux booleans are configured for MPD
  ansible.posix.seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state | default(true) }}"
    persistent: true
  with_items:
    - name: mpd_enable_homedirs
    - name: mpd_use_cifs
      state: "{{ mpd_use_cifs | bool }}"
    - name: mpd_use_nfs
      state: "{{ mpd_use_nfs | bool }}"

- name: Ensure temporary directory is present
  ansible.builtin.tempfile:
    state: directory
  register: tmp_dir
  tags: molecule-idempotence-notest

- name: Ensure MPD SELinux module is present
  ansible.builtin.copy:
    src: mpd_selinux.te
    dest: "{{ tmp_dir.path }}/mpd_selinux.te"
  tags: molecule-idempotence-notest

- name: Ensure MPD SELinux module is activated
  ansible.builtin.command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o mpd_selinux.mod mpd_selinux.te
    - semodule_package -o mpd_selinux.pp -m mpd_selinux.mod
    - semodule -i mpd_selinux.pp
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: false
  tags: molecule-idempotence-notest

- name: Ensure temporary directory is absent
  ansible.builtin.file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
  tags: molecule-idempotence-notest

- name: Firewall configuration
  ansible.builtin.include_tasks: firewall.yml

- name: Ensure MPD socket service is started
  ansible.builtin.systemd:
    name: mpd.socket
    state: started
    enabled: true
    daemon_reload: true

- name: Ensure the MPD database is up to date
  ansible.builtin.command: mpc update
  when: mpd_update | bool
  changed_when: false
  tags: molecule-notest  # Sometime, fail on GitHub action

- name: Ensure MPC use password when called by admin user shell
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    regexp: "^alias mpc="
    line: 'alias mpc="mpc -P {{ mpd_passwords[0].split("@")[0] }}"'
  no_log: true
  when: mpd_passwords is defined

- name: Ensure security MPD package files metadata are in sync
  ansible.builtin.command: rpm --restore mpd # noqa command-instead-of-module
  changed_when: false

- name: Ensure MPD "rpmnew" and "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mpd.conf.rpmnew
    - /etc/mpd.conf.rpmsave
