---

- name: Ensure Dovecot is configured
  ansible.builtin.lineinfile:
    path: "/etc/dovecot/{{ item.file }}"
    regexp: "^#?{{ item.line.split('=')[0] }}="
    line: "{{ item.line }}"
  with_items:
    - line: "protocols = lmtp {{ _dovecot_protocols }}"
      file: "dovecot.conf"
    - line: "login_greeting ="
      file: "dovecot.conf"
      # Mail box
    - line: "mail_location = mdbox:~/mdbox"
      file: "conf.d/10-mail.conf"
      # Authentication
    - line: "auth_username_format = %Ln"
      file: "conf.d/10-auth.conf"
    - line: "disable_plaintext_auth = yes"
      file: "conf.d/10-auth.conf"
      when: "{{ not _dovecot_unsecure | bool }}"
      # Mozilla SSL configuration
      # https://ssl-config.mozilla.org/#server=dovecot&config=modern
    - line: "ssl = {{ _dovecot_unsecure | ternary('yes', 'required') }}"
      file: "conf.d/10-ssl.conf"
    - line: "ssl_min_protocol = LATEST"
      file: "conf.d/10-ssl.conf"
    - line: "ssl_prefer_server_ciphers = no"
      file: "conf.d/10-ssl.conf"
    - line: "ssl_cert = <{{ _tls_crt }}"
      file: "conf.d/10-ssl.conf"
    - line: "ssl_key = <{{ _tls_key }}"
      file: "conf.d/10-ssl.conf"
  when:
    - item.when | default(true)

- name: Ensure unsecure Dovecot protocols are disabled
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-master.conf
    regexp: "^\\s*#?port = {{ item.port }}"
    insertafter: "^\\s*inet_listener {{ item.protocol }} {"
    line: "    port = 0"
    firstmatch: true
  with_items:
    - port: 143
      protocol: imap
      when: "{{ not mail_protocol_imap | bool }}"
    - port: 110
      protocol: pop3
      when: "{{ not mail_protocol_pop3 | bool }}"
  when:
    - item.when

- name: Ensure Dovecot SASL socket is configured
  ansible.builtin.blockinfile:
    marker: "# {mark} SASL SOCKET"
    path: /etc/dovecot/conf.d/10-master.conf
    insertafter: "service auth {"
    block: |
      unix_listener /var/spool/postfix/private/auth {
        mode = 0600
        user = postfix
        group = postfix
      }

- name: Ensure Dovecot LMTP socket is configured
  ansible.builtin.blockinfile:
    marker: "# {mark} LMTP SOCKET"
    path: /etc/dovecot/conf.d/10-master.conf
    insertafter: "service lmtp {"
    block: |
      unix_listener /var/spool/postfix/private/dovecot-lmtp {
        mode = 0600
        user = postfix
        group = postfix
      }

- name: Ensure Dovecot default LMTP socket is removed
  ansible.builtin.replace:
    path: /etc/dovecot/conf.d/10-master.conf
    after: "service lmtp {"
    replace: ""
    regexp: "^\\s*unix_listener lmtp {\\s*#mode = 0666\\s*}$"

- name: Ensure Dovecot service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/dovecot.service.d
    state: directory

- name: Ensure Dovecot systemd service configuration is present
  ansible.builtin.copy:
    src: dovecot_service.conf
    dest: /etc/systemd/system/dovecot.service.d/dovecot.conf
