---

- name: Check if Dovecot configuration was updated by RPM
  ansible.builtin.stat:
    path: /etc/dovecot/dovecot.conf.rpmnew
  register: dovecot_conf_rpmnew

- name: Ensure latest Dovecot configuration from RPM is used
  ansible.builtin.copy:
    remote_src: true
    src: /etc/dovecot/dovecot.conf.rpmnew
    dest: /etc/dovecot/dovecot.conf
  when: dovecot_conf_rpmnew.stat.exists

- name: Ensure Dovecot is configured
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/conf.d/local.conf
    owner: root
    group: root
    mode: '0644'
  register: _dovecot_conf

- name: Ensure Dovecot service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/dovecot.service.d
    state: directory

- name: Ensure Dovecot systemd service configuration is present
  ansible.builtin.copy:
    src: dovecot_service.conf
    dest: /etc/systemd/system/dovecot.service.d/dovecot.conf
  register: _dovecot_service_conf

- name: Ensure security Dovecot package files metadata are in sync
  ansible.builtin.command: rpm --restore dovecot # noqa command-instead-of-module
  changed_when: false

- name: Ensure Dovecot service is re-started
  ansible.builtin.systemd:
    name: postfix
    state: restarted
    daemon_reload: "{{ (_dovecot_service_conf.changed | bool) or (_dovecot_conf.changed | bool) }}"
  changed_when: false

- name: Ensure Dovecot "rpmnew" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmnew"
    state: absent
  with_items:
    - /etc/dovecot/dovecot.conf
    - /etc/dovecot/conf.d/10-auth.conf
    - /etc/dovecot/conf.d/10-mail.conf
    - /etc/dovecot/conf.d/10-master.conf
    - /etc/dovecot/conf.d/10-ssl.conf

- name: Ensure Dovecot "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmsave"
    state: absent
  with_items:
    - /etc/dovecot/dovecot.conf
    - /etc/dovecot/conf.d/10-auth.conf
    - /etc/dovecot/conf.d/10-mail.conf
    - /etc/dovecot/conf.d/10-master.conf
    - /etc/dovecot/conf.d/10-ssl.conf

- name: Ensure Dovecot <2.4.0 configuration files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/dovecot/conf.d/10-auth.conf
    - /etc/dovecot/conf.d/10-mail.conf
    - /etc/dovecot/conf.d/10-master.conf
    - /etc/dovecot/conf.d/10-ssl.conf
