---

- name: Ensure Dovecot and Postfix are installed
  ansible.builtin.dnf:
    state: present
    name:
      - dovecot
      - postfix
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure mail users are presents
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: always
  with_items: "{{ mail_users }}"
  when: mail_users is defined

- name: Ensure mail users aliases are set
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^#?{{ item.user }}:"
    line: '{{ item.user }}:           {{ item.alias }}'
  when: mail_users_aliases is defined
  register: _postfix_aliases
  with_items: "{{ mail_users_aliases }}"

- name: SMTP server configuration
  ansible.builtin.include_tasks: postfix.yml

- name: IMAP/POP server configuration
  ansible.builtin.include_tasks: dovecot.yml

- name: Ensure Fail2ban directory is present
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d/
    state: directory

- name: Ensure Fail2ban is configured
  ansible.builtin.copy:
    src: mail.local
    dest: /etc/fail2ban/jail.d/mail.local

- name: TLS certificate configuration
  ansible.builtin.include_tasks: tls_certificates.yml

- name: Ensure Dovecot and Postfix services are started and enabled at boot
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - dovecot
    - postfix

- name: Firewall configuration
  ansible.builtin.include_tasks: firewall.yml
