---

- name: Ensure Dovecot and Postfix are installed
  dnf:
    state: present
    name:
      - dovecot
      - postfix
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure mail users are presents
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: always
  with_items: "{{ mail_users }}"
  when: mail_users is defined

- name: Ensure mail users aliases are set
  lineinfile:
    path: /etc/aliases
    regexp: "^#?{{ item.user }}:"
    line: '{{ item.user }}:           {{ item.alias }}'
  when: mail_users_aliases is defined
  register: _postfix_aliases
  with_items: "{{ mail_users_aliases }}"

- include_tasks: postfix.yml

- include_tasks: dovecot.yml

- name: Ensure Fail2ban directory is present
  file:
    path: /etc/fail2ban/jail.d/
    state: directory

- name: Ensure Fail2ban is configured
  copy:
    src: mail.local
    dest: /etc/fail2ban/jail.d/mail.local

- include_tasks: tls_certificates.yml

- name: Ensure Dovecot and Postfix services are started and enabled at boot
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - dovecot
    - postfix

- name: Ensure Postfix configuration is valid
  command: postfix check
  changed_when: false

- name: Ensure Postfix aliases are reloaded
  command: newaliases
  when: _postfix_aliases.changed  # noqa no-handler

- name: Ensure Postfix service is re-started
  systemd:
    name: postfix
    state: restarted
  when: _postfix_aliases.changed  # noqa no-handler

- include_tasks: firewall.yml
