---

- name: Ensure TLS certificates are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - src: "{{ mail_tls_certificate | default(None) }}"
      dest: "{{ _tls_crt }}"
      when: "{{ mail_tls_certificate is defined }}"
    - src: "{{ mail_tls_certificate_key | default(None) }}"
      dest: "{{ _tls_key }}"
      mode: "0600"
      when: "{{ mail_tls_certificate_key is defined }}"
    - src: dhparam.pem
      dest: "{{ _tls_dh_params }}"
  when: item.when | default(true)

- name: Self-signed certificate warning
  debug:
    msg: "Security Warning, It is recommanded to provide a certificate signed
          by a trusted CA"
  when: mail_tls_certificate is not defined

- name: Ensure at least an unsecure self-signed certificate is present
  command: "openssl req -x509 -newkey rsa:4096
            -keyout {{ _tls_key }} -out {{ _tls_crt }}
            -days 3650 -nodes -subj '/CN={{ mail_domain }}'"
  args:
    creates: "{{ _tls_crt }}"
  when: mail_tls_certificate is not defined
