---

- name: Ensure SSH public key is authorized
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ common_ssh_authorized_key }}"
    state: present
  no_log: true
  when: common_ssh_authorized_key is defined

- name: Ensure current user password is set
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ common_admin_password }}"
  no_log: true
  when: common_admin_password is defined
