---

- name: Check if Grub default configuration was updated by RPM
  ansible.builtin.stat:
    path: /etc/default/grub.rpmnew
  register: _grub_default_rpmnew

- name: Ensure latest Grub default configuration from RPM is used
  ansible.builtin.copy:
    remote_src: true
    src: /etc/default/grub.rpmnew
    dest: /etc/default/grub
  when: _grub_default_rpmnew.stat.exists

- name: Ensure Grub options are configured
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: true
    state: "{{ (item.when | default(true)) | ternary('present', 'absent') }}"
  with_items:
    - line: 'GRUB_TIMEOUT="{{ common_grub_timeout }}"'
      regexp: "^GRUB_TIMEOUT="
    - line: 'GRUB_HIDDEN_TIMEOUT="{{ common_grub_hidden_timeout }}"'
      regexp: "^GRUB_HIDDEN_TIMEOUT="
    - line: 'GRUB_HIDDEN_TIMEOUT_QUIET="true"'
      regexp: "^GRUB_HIDDEN_TIMEOUT_QUIET="
    - line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ _grub_cmdline_linux_default | flatten | join(" ") }}"'
      regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
      when: "{{ (_grub_cmdline_linux_default | flatten | length) > 0 }}"

- name: Ensure Grub auto hide is configured
  ansible.builtin.command: "grub2-editenv - {{ common_grub_auto_hide |
            ternary('set menu_auto_hide=1', 'unset menu_auto_hide') }}"
  changed_when: false

- name: Ensure Ansible "python3-pexpect" requirement is installed
  ansible.builtin.dnf:
    state: present
    name: python3-pexpect
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _pg_python3_pexpect
  until: _pg_python3_pexpect is successful
  when: common_grub_password is defined

- name: Ensure Grub password is set
  when: common_grub_password is defined
  block:
    - name: Ensure Grub password is set
      ansible.builtin.expect:
        command: grub2-setpassword
        responses:
          ".*password": "{{ common_grub_password }}"
      changed_when: false
  always:
    - name: Ensure Ansible "python3-pexpect" requirement is removed
      ansible.builtin.dnf:
        state: absent
        name: python3-pexpect
      when: _pg_python3_pexpect.changed  # noqa no-handler

- name: Ensure Grub password is unset
  ansible.builtin.file:
    path: /boot/grub2/user.cfg
    state: absent
  when: common_grub_password is not defined

- name: Ensure Grub configuration is applied
  ansible.builtin.command: "grub2-mkconfig -o {{ item }}"
  changed_when: false
  with_items:
    - /boot/efi/EFI/fedora/grub.cfg
    - /boot/grub2/grub.cfg

- name: Ensure Grub "rpmnew" and "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/grub.rpmnew
    - /etc/default/grub.rpmsave
