---

- name: Ensure root access via console device is disabled
  ansible.builtin.file:
    path: /etc/securetty
    state: touch
    mode: "0600"
    modification_time: preserve
    access_time: preserve
  when: common_os_hardening | bool

- name: Ensure Kernel sysctl hardening is set
  ansible.builtin.copy:
    src: sysctl-hardening.conf
    dest: /etc/sysctl.d/99-hardening.conf
    mode: "0600"
  register: _sysctl
  when: common_os_hardening | bool
  notify: kernel_modules_disabled

- name: Ensure Kernel user namespaces are disabled
  ansible.builtin.copy:
    src: sysctl-hardening-user-namespaces-disabled.conf
    dest: /etc/sysctl.d/99-hardening-user-namespaces-disabled.conf
    mode: "0600"
  when:
    - common_os_hardening | bool
    - common_os_hardening_disable_user_namespaces | bool

- name: Ensure Kernel module loading is temporary allowed during Ansible operation
  ansible.builtin.file:
    path: /etc/sysctl.d/99-hardening-kernel-modules-disabled.conf
    state: absent
  when: common_os_hardening | bool
  notify: kernel_modules_disabled

- name: Ensure IPv6 privacy extensions are enabled in systemd
  ansible.builtin.copy:
    src: networkd-ipv6-privacy-extensions.conf
    dest: /etc/systemd/network/ipv6-privacy-extensions.conf
    mode: "0600"
  register: _ipv6_privacy_extensions
  when: common_os_hardening | bool

- name: Ensure coredump configuration directory is present
  ansible.builtin.file:
    path: /etc/systemd/coredump.conf.d
    state: directory
  when: common_os_hardening | bool

- name: Ensure coredump storage is disabled in systemd
  ansible.builtin.copy:
    src: coredump-disabled.conf
    dest: /etc/systemd/coredump.conf.d/disabled.conf
    mode: "0600"
  when: common_os_hardening | bool

- name: Ensure Systemd coredump socket and service are disabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: true
  ignore_errors: true  # noqa ignore-errors
  with_items:
    - systemd-coredump
    - systemd-coredump.socket

- name: Ensure Systemd debug-shell service is disabled
  ansible.builtin.systemd:
    name: debug-shell
    enabled: false
    state: stopped
    masked: true
  ignore_errors: true  # noqa ignore-errors

- name: Ensure security limits configuration directory is present
  ansible.builtin.file:
    path: /etc/security/limits.d
    state: directory
  when: common_os_hardening | bool

- name: Ensure coredump is disabled in security limits configuration
  community.general.pam_limits:
    dest: /etc/security/limits.d/50-hard-core.conf
    domain: "*"
    limit_type: hard
    limit_item: core
    value: "0"
  when: common_os_hardening | bool

- name: Ensure rng-tools is installed
  ansible.builtin.dnf:
    state: present
    name: rng-tools
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful
  when:
    - common_os_hardening | bool
    - not (_ostree | bool)

- name: Ensure rng-tools is installed
  community.general.rpm_ostree_pkg:
    state: present
    name: rng-tools
  when:
    - common_os_hardening | bool
    - _ostree | bool

- name: Ensure rngd is enabled
  ansible.builtin.systemd:
    name: rngd
    enabled: "{{ common_os_hardening | bool }}"
    state: "{{ (common_os_hardening | bool) | ternary('started', 'stopped') }}"

- name: Ensure vulnerable or rarely used Kernel modules loading is disallowed
  ansible.builtin.template:
    src: modprobe-hardening.conf.j2
    dest: /etc/modprobe.d/hardening.conf
    mode: "0600"
  when: common_os_hardening | bool

- name: Ensure interactive session timeout is set
  ansible.builtin.lineinfile:
    path: /etc/profile.d/tmout.sh
    create: true
    regexp: "TMOUT="
    line: "declare -xr TMOUT={{ common_os_hardening_interactive_timeout }}"
  when: common_os_hardening | bool

- name: Ensure hardening is disabled
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when: not (common_os_hardening | bool)
  register: _disable_hardening
  with_items:
    - /etc/securetty
    - /etc/sysctl.d/99-hardening.conf
    - /etc/systemd/network/ipv6-privacy-extensions.conf
    - /etc/systemd/coredump.conf.d/disabled.conf
    - /etc/security/limits.d/50-hard-core.conf
    - /etc/modprobe.d/hardening.conf
    - /etc/profile.d/tmout.sh

- name: Ensure networkd is restarted
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  changed_when: false
  when: _ipv6_privacy_extensions.changed or _disable_hardening.changed  # noqa no-handler

- name: Ensure Kernel sysctl is reloaded
  ansible.builtin.command: /usr/sbin/sysctl --system
  changed_when: false
  when: _sysctl.changed or _disable_hardening.changed  # noqa no-handler

- name: Ensure Ansible "crypto-policies-scripts" requirement is installed
  ansible.builtin.dnf:
    state: present
    name: crypto-policies-scripts
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _common_crypto_policies_scripts
  until: _common_crypto_policies_scripts is successful
  when: not (_ostree | bool)

- name: Ensure Ansible "crypto-policies-scripts" requirement is installed
  community.general.rpm_ostree_pkg:
    name: crypto-policies-scripts
    state: present
  when: _ostree | bool

- name: Ensure cryptography policies are configured
  block:
    - name: Ensure cryptography policies are configured
      ansible.builtin.command: "{{ item }}"
      changed_when: false
      with_items:
        - "update-crypto-policies --set {{ common_os_hardening_fips | bool | ternary('FIPS', 'DEFAULT') }}"
        - "fips-mode-setup --{{ common_os_hardening_fips | bool | ternary('en', 'dis') }}able"

  always:
    - name: Ensure Ansible "crypto-policies-scripts" requirement is removed
      ansible.builtin.dnf:
        state: absent
        name: crypto-policies-scripts
      when:
        - _common_crypto_policies_scripts.changed  # noqa no-handler
        - not (_ostree | bool)

    - name: Ensure Ansible "crypto-policies-scripts" requirement is removed
      community.general.rpm_ostree_pkg:
        name: crypto-policies-scripts
        state: absent
      when:
        - _common_crypto_policies_scripts.changed  # noqa no-handler
        - _ostree | bool
