---

- include_tasks: ca_certificates.yml
  when: common_ca_certificates is defined

- include_tasks: dns.yml

- include_tasks: hardening_os.yml
  when: common_os_hardening | bool

- include_tasks: hardening_ssh.yml
  when: common_ssh_hardening | bool

- include_tasks: admin_credentials.yml

- include_tasks: ntp.yml
  when: common_ntp_server is defined

- include_tasks: grub.yml

- include_tasks: dnf.yml

- include_tasks: mount_nfs.yml
  when: common_nfs_mount is defined

- include_tasks: mount_smb.yml
  when: common_smb_mount is defined

- include_tasks: fail2ban.yml

- include_tasks: mail.yml
  when: common_mail_smtp_host is defined

- include_tasks: firewall.yml
