---

- name: Ensure hostname is set
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
  when: common_hostname is defined

- name: Ensure Anaconda Kickstart file is absent
  ansible.builtin.file:
    path: /root/anaconda-ks.cfg
    state: absent

- name: Journald configuration
  ansible.builtin.include_tasks: journal.yml
  when: common_journal_disk_max_size is defined or common_journal_memory_max_size is defined

- name: CA certificates configuration
  ansible.builtin.include_tasks: ca_certificates.yml
  when: common_ca_certificates is defined

- name: DNS configuration
  ansible.builtin.include_tasks: dns.yml

- name: PAM configuration
  ansible.builtin.include_tasks: pam.yml

- name: Auditd configuration
  ansible.builtin.include_tasks: audit.yml

- name: OS Hardening
  ansible.builtin.include_tasks: hardening_os.yml
  when: common_os_hardening | bool

- name: SSH Hardening
  ansible.builtin.include_tasks: hardening_ssh.yml

- name: Admin credentials configuration
  ansible.builtin.include_tasks: admin_credentials.yml

- name: NTP configuration
  ansible.builtin.include_tasks: ntp.yml

- name: Boot configuration
  ansible.builtin.include_tasks: grub.yml

- name: DNF configuration
  ansible.builtin.include_tasks: dnf.yml
  when: not (_ostree | bool)

- name: NFS mounts configuration
  ansible.builtin.include_tasks: mount_nfs.yml
  when: common_nfs_mount is defined

- name: SMB mounts configuration
  ansible.builtin.include_tasks: mount_smb.yml
  when: common_smb_mount is defined

- name: Fail2ban configuration
  ansible.builtin.include_tasks: fail2ban.yml

- name: Email configuration
  ansible.builtin.include_tasks: mail.yml
  when: common_mail_smtp_host is defined

- name: Firewall configuration
  ansible.builtin.include_tasks: firewall.yml
