---

- name: Ensure SMB client requirements are installed
  ansible.builtin.dnf:
    state: present
    name: cifs-utils
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure SMB target mount directories are present
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ common_smb_mount }}"

- name: Creates SMB credentials files
  ansible.builtin.copy:
    content: "username={{ item.username }}\npassword={{ item.password }}\ndomain={{ item.domain }}\n"
    dest: "/etc/samba/credentials_{{ item.path | hash('blake2b') }}"
    owner: root
    group: root
    mode: "0600"
  with_items: "{{ common_smb_mount }}"
  when: item.username is defined

- name: Mount SMB shares
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    # TODO
    opts: "{{ item.opts | default(omit) }}" # CONDITIONAL ADD credentials=/etc/samba/credentials_{{ item.path | hash('blake2b') }}
    fstype: cifs
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ common_smb_mount }}"
