---

- name: Ensure SMB client requirements are installed
  dnf:
    state: present
    name: cifs-utils
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure SMB target mount directories are present
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ common_smb_mount }}"

- name: Mount SMB shares
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts | default(omit) }}"
    fstype: cifs
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ common_smb_mount }}"
