---

- name: Ensure Chrony is configured to use specified NTP server
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: "^pool "
    line: "pool {{ common_ntp_server }} iburst{{ common_nts | ternary(' nts', '') }}"

- name: Ensure Chrony is restarted
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
  changed_when: false
