---
galaxy_info:
  author: JGoutin
  description: This Ansible role installs PostgreSQL on Fedora.
  license: GPL-3.0
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions:
        - "41"
  galaxy_tags:
    - fedora
    - system
    - postgresql

dependencies: []
