---
galaxy_info:
  author: JGoutin
  description: This Ansible role installs Valkey on Fedora.
  license: GPL-3.0
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - "38"
        - "37"
  galaxy_tags:
    - fedora
    - system
    - valkey

dependencies: []
