{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# Roles requirements
# - dev-sec.os-hardening: findutils, procps-ng
# - dev-sec.ssh-hardening: openssh-clients, openssh-server

RUN echo "retries=0" >> /etc/dnf/dnf.conf && \
dnf --assumeyes install --setopt=install_weak_deps=False \
    findutils \
    openssh-clients \
    openssh-server \
    procps-ng \
    python3 \
    python3-dnf \
    sudo \
    systemd
