---

- name: Ensure Squid DNF repositories mirrors updater utility is present
  ansible.builtin.copy:
    src: squid_dnf_mirrors.py
    dest: /usr/local/bin/squid_dnf_mirrors
    owner: root
    group: root
    mode: "0744"

- name: Ensure Squid DNF repositories mirrors updater configuration file is present
  ansible.builtin.file:
    path: /etc/squid/dnf_mirrors
    state: touch
    mode: "0640"
    owner: root
    group: squid
    modification_time: preserve
    access_time: preserve

- name: Ensure Squid DNF repositories mirrors updater service units are present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - squid_dnf_mirrors.service
    - squid_dnf_mirrors.timer

- name: Ensure DNF repositories mirrors updater service is started and enabled at boot
  ansible.builtin.systemd:
    name: squid_dnf_mirrors.timer
    state: started
    enabled: true
    daemon_reload: true
