---

- name: Ensure Squid is installed
  dnf:
    state: present
    name: squid
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure Squid configuration is present
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf

- name: Ensure Squid CA certificate is present
  copy:
    src: "{{ squid_ssl_bump_ca }}"
    dest: "{{ _tls_ca }}"
    owner: root
    group: squid
    mode: 0640
  when: squid_ssl_bump_ca is defined

- name: Ensure Squid TLS database is initialized
  command: "/usr/lib64/squid/security_file_certgen -c -s {{ _tls_db }} -M 4MB"
  args:
    creates: "{{ _tls_db }}"
  when: squid_ssl_bump_ca is defined

- name: Ensure Squid TLS database is configured
  file:
    path: "{{ _tls_db }}"
    state: directory
    owner: squid
    group: squid
    mode: 0750
    setype: squid_cache_t
    recurse: true
  when: squid_ssl_bump_ca is defined

- name: Ensure Squid service parent directory is present
  file:
    path: /etc/systemd/system/squid.service.d
    state: directory

- name: Ensure Squid systemd service configuration is present
  copy:
    src: squid_service.conf
    dest: /etc/systemd/system/squid.service.d/squid.conf

- name: Ensure Squid service is started and enabled at boot
  systemd:
    name: squid
    state: started
    enabled: true
    daemon_reload: true

- include_tasks: dnf_mirrors.yml

- include_tasks: firewall.yml
