---
- name: Retrieve Netdata public unique ID
  ansible.builtin.slurp:
    src: /var/lib/netdata/registry/netdata.public.unique.id
  register: _netdata_public_id

- name: Ensure Netdata configuration directory is present
  ansible.builtin.file:
    path: /etc/netdata/go.d
    state: directory
    mode: '0755'

- name: Ensure Netdata collectors are configured
  ansible.builtin.template:
    src: "netdata_{{ item }}.conf.j2"
    dest: "/etc/netdata/go.d/{{ item }}.conf"
    mode: '0644'
  notify: netdata_restarted
  with_items:
    - squid
    - squidlog

- name: Ensure Squid log rotation service units are present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - squid_logrotate.service
    - squid_logrotate.timer

- name: Ensure Squid log rotation service is started and enabled at boot
  ansible.builtin.systemd:
    name: squid_logrotate.timer
    state: started
    enabled: true
    daemon_reload: true
