---

- name: Ensure temporary directory is present
  ansible.builtin.tempfile:
    state: directory
  register: tmp_dir
  tags: molecule-idempotence-notest

- name: Ensure httpd access SELinux module is present
  ansible.builtin.copy:
    src: squid_t_fix.te
    dest: "{{ tmp_dir.path }}/squid_t_fix.te"
  tags: molecule-idempotence-notest

- name: Ensure httpd access SELinux module is activated
  ansible.builtin.command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o squid_t_fix.mod squid_t_fix.te
    - semodule_package -o squid_t_fix.pp -m squid_t_fix.mod
    - semodule -i squid_t_fix.pp
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: false
  tags: molecule-idempotence-notest

- name: Ensure temporary directory is absent
  ansible.builtin.file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
  tags: molecule-idempotence-notest
