---

- name: Ensure CoTURN is installed from Fedora repository
  dnf:
    state: present
    name: coturn
    install_weak_deps: false
  retries: 10
  delay: 1
  register: _
  until: _ is successful

- name: Ensure CoTURN is configured
  lineinfile:
    path: /etc/coturn/turnserver.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line | default(omit) }}"
    owner: root
    group: coturn
    mode: 0640
  with_items:
    - regexp: '^#?\s*listening-port='
      line: "listening-port={{ coturn_listening_port }}"
    - regexp: '^#?\s*tls-listening-port='
      line: "tls-listening-port={{ coturn_tls_listening_port }}"
    - regexp: '^#?\s*fingerprint'
      line: "fingerprint"
    - regexp: '^#?\s*use-auth-secret'
      line: "use-auth-secret"
    - regexp: '^#?\s*static-auth-secret='
      line: "static-auth-secret={{ coturn_static_auth_secret }}"
    - regexp: '^#?\s*realm='
      line: "realm={{ coturn_realm }}"
    - regexp: '^#?\s*total-quota='
      line: "total-quota={{ coturn_total_quota }}"
    - regexp: '^#?\s*bps-capacity='
      line: "bps-capacity={{ coturn_bps_capacity }}"
    - regexp: '^#?\s*no-multicast-peers'
      line: "no-multicast-peers"
    - regexp: '^#?\s*stale-nonce'
      line: "stale-nonce"
    - regexp: '^#?\s*no-tlsv1\s*$'
      line: "no-tlsv1"
    - regexp: '^#?\s*no-tlsv1_1'
      line: "no-tlsv1_1"
    - regexp: '^#?\s*dh-file='
      line: "dh-file={{ _tls_dh_params }}"
    - regexp: '^#?\s*cipher-list='
      line: cipher-list="{{ _tls_cipher }}"
    - regexp: '^#?\s*pkey='
      line: "pkey={{ _tls_key }}"
    - regexp: '^#?\s*cert='
      line: "cert={{ _tls_crt }}"

- include_tasks: tls_certificates.yml

- name: Ensure CoTURN service parent directory is present
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: Ensure CoTURN systemd service configuration is present
  copy:
    src: coturn_service.conf
    dest: /etc/systemd/system/coturn.service.d/coturn.conf

- name: Ensure CoTURN service is started and enabled at boot
  block:
    - name: Ensure CoTURN service is started and enabled at boot
      systemd:
        name: coturn
        state: started
        enabled: true
        daemon_reload: true
  rescue:
    - name: Show service status on error
      command: systemctl status coturn --no-pager  # noqa command-instead-of-module
      failed_when: true
      changed_when: false

- include_tasks: firewall.yml
