---

- name: Ensure TLS certificates are present
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.mode | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - src: "{{ coturn_tls_certificate | default(None) }}"
      dest: "{{ _tls_crt }}"
      mode: "0640"
      group: coturn
      when: "{{ coturn_tls_certificate is defined }}"
    - src: "{{ coturn_tls_certificate_key | default(None) }}"
      dest: "{{ _tls_key }}"
      mode: "0640"
      group: coturn
      when: "{{ coturn_tls_certificate_key is defined }}"
    - src: dhparam.pem
      dest: "{{ _tls_dh_params }}"
  when: item.when | default(true)

- name: Ensure at least an unsecure self-signed certificate is present
  when: coturn_tls_certificate is not defined
  block:

    - name: Ensure Ansible "openssl" requirement is installed
      ansible.builtin.dnf:
        state: present
        name: openssl
        install_weak_deps: false
      retries: 10
      delay: 1
      register: _openssl
      until: _openssl is successful

    - name: Self-signed certificate warning
      ansible.builtin.debug:
        msg: "Security Warning, It is recommended to provide a certificate signed
              by a trusted CA"

    - name: Ensure at least an unsecure self-signed certificate is present
      ansible.builtin.command: "openssl req -x509 -newkey rsa:4096
                -keyout {{ _tls_key }} -out {{ _tls_crt }}
                -days 3650 -nodes -subj '/CN={{ coturn_realm }}'"
      args:
        creates: "{{ _tls_crt }}"

  always:
    - name: Ensure Ansible "openssl" requirement is removed
      ansible.builtin.dnf:
        state: absent
        name: openssl
      when: _openssl.changed  # noqa no-handler
